version: '3.8'

services:
  loja:
    build: .
    command: npm start
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  db:
    image: postgres
    ports:
      - 1414:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker

  adminer:
    image: adminer
    ports:
      - 8888:8080

volumes:
  node_modules:
