version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 1414:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker

  adminer:
    image: adminer
    ports:
      - 8080:8080
